//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassandra.LinqPad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources/Error16.png")]
        public string ErrorURIIcon16 {
            get {
                return ((string)(this["ErrorURIIcon16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources/Information16.png")]
        public string InfoURIIcon16 {
            get {
                return ((string)(this["InfoURIIcon16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press the Add button to add this node to the connection list.")]
        public string HostNodeInfoToolTip {
            get {
                return ((string)(this["HostNodeInfoToolTip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources/OK16.png")]
        public string OKURI16 {
            get {
                return ((string)(this["OKURI16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources/Alerts16.png")]
        public string AlertURI16 {
            get {
                return ((string)(this["AlertURI16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources/Network16.png")]
        public string NetworkURI16 {
            get {
                return ((string)(this["NetworkURI16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources/Move Up (Arrow) Green16.png")]
        public string UPURI16 {
            get {
                return ((string)(this["UPURI16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources/Move Down (Arrow) Red16.png")]
        public string DownURI16 {
            get {
                return ((string)(this["DownURI16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources/Plugin16.png")]
        public string PlugInURI16 {
            get {
                return ((string)(this["PlugInURI16"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Click Next to Select Keyspace and Table")]
        public string NextConnectionToolTip {
            get {
                return ((string)(this["NextConnectionToolTip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9042")]
        public int CQLPort {
            get {
                return ((int)(this["CQLPort"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources/Query16.png")]
        public string QeuryURI16 {
            get {
                return ((string)(this["QeuryURI16"]));
            }
            set {
                this["QeuryURI16"] = value;
            }
        }
    }
}
